// Firebase Config
export const FIREBASECONFIG_APIKEY = process.env.NEXT_PUBLIC_FIREBASECONFIG_APIKEY;
export const FIREBASECONFIG_AUTHDOMAIN = process.env.NEXT_PUBLIC_FIREBASECONFIG_AUTHDOMAIN;
export const FIREBASECONFIG_PROJECTID = process.env.NEXT_PUBLIC_FIREBASECONFIG_PROJECTID;
export const FIREBASECONFIG_STORAGEBUCKET = process.env.NEXT_PUBLIC_FIREBASECONFIG_STORAGEBUCKET;
export const FIREBASECONFIG_MESSAGINGSENDERID = process.env.NEXT_PUBLIC_FIREBASECONFIG_MESSAGINGSENDERID;
export const FIREBASECONFIG_APPID = process.env.NEXT_PUBLIC_FIREBASECONFIG_APPID;
export const FIREBASECONFIG_MEASUREMENTID = process.env.NEXT_PUBLIC_FIREBASECONFIG_MEASUREMENTID;